apiVersion: v1
kind: Service
metadata:
  name: whisper-service
spec:
  type: NodePort
  selector:
    app: whisper
  ports:
    - protocol: TCP
      port: 5200
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5200
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30303
